const fs=require('node:fs');const path=require('node:path');const ts=require('typescript');const vm=require('node:vm');const assert=require('node:assert/strict');
const input=fs.readFileSync('content/canon/core.ts','utf8');const compiled=ts.transpileModule(input,{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;const sandbox={exports:{}};vm.runInNewContext(compiled,sandbox);const {readCanon,publicRecords}=sandbox.exports;
for(const status of ['DRAFT','UNKNOWN','DEPRECATED'])assert.equal(readCanon({status,value:'must not appear'}),undefined);
assert.equal(readCanon({status:'CANON',value:'approved'}),'approved');assert.equal(publicRecords(['CANON','DRAFT','UNKNOWN','DEPRECATED'].map((status,i)=>({id:String(i),status,source:'test'}))).length,1);
const routes=['','about','world','characters','scenes','creatures','stories','philosophy'];const titles=new Set();for(const route of routes){const html=fs.readFileSync(path.join('out',route,'index.html'),'utf8');const title=html.match(/<title[^>]*>(.*?)<\/title>/)[1];titles.add(title);assert.match(title,/Mang Flux/);assert.match(html,/property="og:site_name" content="芒 · Mang Flux"/);assert.match(html,/name="description"/);assert.doesNotMatch(html,/芒头|MANG TOU|青陆|苍陆|赤陆|听潮城|待核对|概念示意|待作者定稿/)}assert.equal(titles.size,routes.length);
function files(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?files(path.join(dir,e.name)):[path.join(dir,e.name)])}for(const file of files('out/_next').filter(x=>/\.(js|json)$/.test(x))){assert.doesNotMatch(fs.readFileSync(file,'utf8'),/青陆|苍陆|赤陆|听潮城|断流之夜|芒头|MANG TOU|待核对|待作者定稿/)}
for(const name of ['map','landscape','characters']){assert.equal(fs.existsSync(`public/art/${name}.webp`),false);assert.equal(fs.existsSync(`assets/deprecated/${name}.webp`),true)}assert.equal(fs.readdirSync('public/art/portfolio').filter(n=>n.endsWith('.webp')).length,18);assert.equal(fs.existsSync('public/audio/mang-theme.mp3'),true);assert.equal(fs.existsSync('out/audio/mang-theme.mp3'),true);
console.log('CANON states, eight unique SEO titles, withdrawn text absent from export, 18 original images retained, generated images offline, supplied soundtrack present: PASS');

