const {chromium}=require('@playwright/test');
const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{
const browser=await chromium.launch({executablePath:process.env.BROWSER_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const context=await browser.newContext();const page=await context.newPage();const errors=[],badResponses=[],results=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)badResponses.push(`${r.status()} ${r.url()}`)});
const base='http://127.0.0.1:3000';const widths=[375,390,768,1024,1440,1920];const routes=['/','/about/','/world/','/characters/','/scenes/','/creatures/','/stories/','/philosophy/'];
fs.mkdirSync('output/v11-qa',{recursive:true});
for(const width of widths){
 await page.setViewportSize({width,height:width<700?844:1000});await page.goto(base);await page.evaluate(()=>sessionStorage.clear());await page.reload();await page.getByRole('button',{name:'进入世界',exact:true}).waitFor();
 assert.equal(await page.locator('header,footer').count(),0);assert.equal(await page.locator('audio').count(),0);assert.equal(await page.locator('.entry-art').getAttribute('src'),'/art/portfolio/valley.webp');
 await page.screenshot({path:`output/v11-qa/entry-${width}.png`,animations:'disabled'});const start=Date.now();await page.getByRole('button',{name:'进入世界',exact:true}).click();await page.locator('#main').waitFor();assert.ok(Date.now()-start>=800,'entry fade');assert.equal(await page.evaluate(()=>sessionStorage.getItem('enteredMangWorld')),'true');
 for(const route of routes){const response=await page.goto(base+route,{waitUntil:'networkidle'});assert.equal(response.status(),200);assert.equal(await page.locator('.world-entry').count(),0);assert.equal(await page.locator('h1').count(),1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,`${width} ${route} overflow`);
 const body=await page.locator('body').innerText();assert.doesNotMatch(body,/芒头|MANG TOU|青陆|苍陆|赤陆|待核对|待作者定稿|概念示意|原网站扩写内容|三大陆|五大禁区/);assert.ok((await page.title()).includes('Mang Flux'));
 const imgs=page.locator('img');for(let i=0;i<await imgs.count();i++){await imgs.nth(i).scrollIntoViewIfNeeded();await imgs.nth(i).evaluate(img=>img.decode());assert.ok((await imgs.nth(i).getAttribute('src')).startsWith('/art/portfolio/'));}
 await page.locator('footer').scrollIntoViewIfNeeded();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`output/v11-qa/${route==='/'?'home':route.replaceAll('/','')}-${width}.png`,fullPage:true,animations:'disabled'});results.push(`${width}px ${route} PASS`);
 }
}
await page.setViewportSize({width:1440,height:1000});await page.goto(base+'/world/');await page.getByRole('button',{name:'区域',exact:true}).click();assert.equal(await page.locator('.structure-node').count(),3);await page.getByRole('button',{name:'打开区域 02档案',exact:true}).hover();assert.match(await page.locator('.region-detail').innerText(),/区域 02/);await page.getByRole('button',{name:'打开区域 02档案',exact:true}).click();await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);await page.getByRole('button',{name:'全部',exact:true}).click();await page.getByRole('button',{name:'放大地图',exact:true}).click();assert.match(await page.locator('.structure-canvas').getAttribute('style'),/125%/);await page.getByRole('button',{name:'重置地图缩放'}).click();results.push('Map hover, modal, filtering, zoom PASS');
await page.goto(base+'/characters/');await page.locator('.character-card').first().click();await page.getByRole('dialog').waitFor();assert.doesNotMatch(await page.getByRole('dialog').innerText(),/身份|出身|芒性|经历|能力|待核对/);await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.className),'character-card');results.push('Character optional fields, dialog and focus return PASS');
await page.goto(base+'/scenes/');await page.locator('.gallery-item').first().click();await page.getByRole('dialog').waitFor();assert.match(await page.getByRole('dialog').innerText(),/雾殷谷/);await page.getByRole('button',{name:'下一幅作品'}).click();assert.match(await page.getByRole('dialog').innerText(),/场景档案 02/);await page.keyboard.press('Escape');results.push('Gallery pagination and dialog PASS');
await page.goto(base+'/stories/');assert.equal(await page.getByRole('heading',{name:'故事章节',exact:true}).count(),0);
await page.setViewportSize({width:390,height:844});await page.goto(base+'/');await page.getByRole('button',{name:'打开导航'}).click();await page.keyboard.press('Shift+Tab');assert.equal(await page.locator('button[aria-label="关闭导航"]').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Tab');assert.equal(await page.locator('nav a').first().evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Escape');assert.equal(await page.getByRole('button',{name:'打开导航'}).getAttribute('aria-expanded'),'false');await page.getByRole('button',{name:'打开导航'}).click();await page.getByRole('navigation').getByRole('link',{name:'地图',exact:true}).click();await page.waitForURL('**/world/');await page.getByRole('button',{name:'打开区域 01档案',exact:true}).click();await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');await page.locator('.brand').click();await page.waitForURL(base+'/');assert.equal(await page.locator('.world-entry').count(),0);assert.equal(await page.locator('.ambient-toggle').isDisabled(),true);results.push('Mobile drawer keyboard loop, route, map tap, logo, audio fallback PASS');
const deep=await browser.newPage();await deep.goto(base+'/characters/');await deep.locator('.brand').click();await deep.waitForURL(base+'/');assert.equal(await deep.locator('.world-entry').count(),0);await deep.close();
const fresh=await browser.newPage({reducedMotion:'reduce'});await fresh.goto(base);await fresh.getByRole('button',{name:'进入世界'}).waitFor();assert.equal(await fresh.locator('.entry-copy').evaluate(e=>getComputedStyle(e).animationName),'none');await fresh.getByRole('button',{name:'进入世界'}).click();await fresh.locator('#main').waitFor();await fresh.close();results.push('Fresh session, direct deep link and reduced motion PASS');
const blocked=await browser.newPage();await blocked.addInitScript(()=>{Storage.prototype.getItem=()=>{throw new DOMException('Blocked','SecurityError')};Storage.prototype.setItem=()=>{throw new DOMException('Blocked','SecurityError')}});await blocked.goto(base);await blocked.getByRole('button',{name:'进入世界'}).click();await blocked.locator('#main').waitFor();await blocked.close();results.push('Storage unavailable fallback PASS');
assert.deepEqual(errors,[]);assert.deepEqual(badResponses,[]);results.push('Runtime/console errors and HTTP asset errors: NONE');fs.writeFileSync('output/v11-qa/results.txt',results.join('\n'));console.log(results.join('\n'));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
